config/routes.rb
Rails.application.routes.draw do
  # get 'home/zipcode'
  root'home#index', as: 'home_index'

  post "zipcode" => 'home#zipcode'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    require 'net/http'
    require 'json'
    
    @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=64151&distance=0&API_KEY=A1931E82-710B-4C30-849A-2F1034D7EE51'    
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)
  
    # Check for empty return result
    if @output.empty?
        @final_output = "Error"
    elsif !@output
      @final_output = "Error"
    else 
      @final_output = @output[0]['AQI']  
    end
    
    if @final_output == "Error"
      api_color = "gray"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "0 - 50 Good"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "51 - 100 Mooderate"
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "101 - 150 Unhealthy for Sensitive Groups (USG)"
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "151 - 200 Unhealthy"
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "201 - 300 Very Unhealthy"
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "maroon"
      @api_description = "301 - 500 Hazardous"
    
    end
  end

  def zipcode 
    @zip_query = params[:zipcode]
    
    if params[:zipcode] == ""
      @zip_query = "Hey you forgot to enter a zipcode!"
    elsif params[:zipcode]
      # Do Api stuff
  
      require 'net/http'
      require 'json'
      @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + "#{@zip_query}" + '&distance=0&API_KEY=A1931E82-710B-4C30-849A-2F1034D7EE51'    
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
    
      # Check for empty return result
      if @output.empty?
          @final_output = "Error"
      elsif !@output
        @final_output = "Error"
      else 
        @final_output = @output[0]['AQI']  
      end
      
      if @final_output == "Error"
        api_color = "gray"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = "0 - 50 Good"
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = "51 - 100 Mooderate"
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = "101 - 150 Unhealthy for Sensitive Groups (USG)"
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = "151 - 200 Unhealthy"
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = "201 - 300 Very Unhealthy"
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "maroon"
        @api_description = "301 - 500 Hazardous"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <%= link_to "My Ozone", home_index_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
     
     
    </ul>
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control mr-sm-2" %> 
        <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for my neighborhood in Kansas City.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br/>
  
  
</div>

<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for the <%= @zip_query %> zipcode.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br/>
  
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
        <br/>
      <%= yield %>
    </div>
  </body>
</html>